### ISSUE TITLE
Error during deployment: Service plan local-entry-point not found

### ISSUE THREAD

**Issue by thisisevanfox** [cap-js/incidents-app#100]
Hello CAP Team,

I'm following the tutorial [Creating Local Entry Point Business Solutions](https://help.sap.com/docs/build-work-zone-standard-edition/sap-build-work-zone-standard-edition/creating-local-entry-point-business-solutions), which references this repository. According to [SAP What's New](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Component=SAP+Build+Work+Zone,+standard+edition&locale=en-US), the `Local Entry Point Business Solutions` feature should have been available since April 17, 2025.

In the tutorial, it says: `Create an instance on service plan local-entry-point.`

The mta.yaml example also uses:
```yaml
- name: incidents-build-workzone-service
  parameters:
    config:
      providerId: ga-${org}-${space}
      exposureId: ga.service
    service-plan: local-entry-point
    service: build-workzone-standard
  type: org.cloudfoundry.managed-service
```

However, in my Subaccount (Region: eu10-004, Commercial Model: Pay-As-You-Go), the available service plans for SAP Build Work Zone, standard edition are only `standard` and `foundation`. There is no `local-entry-point` plan available. Additionally, when checking in the Discovery Center, I can also only find the `standard` and `foundation` plans for SAP Build Work Zone, standard edition.

As a result, the deployment fails with the error: `Service plan local-entry-point not found.`

Could you please advise if additional steps are required to enable the `local-entry-point` service plan, or if it will be made available soon in `eu10-004`?

Thanks a lot for your support!

Best regards,
Johannes
